<?xml version="1.0" encoding="utf-8"?><Database Name="SasmmlungMS" Class="DataClassesSammlungenDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=SasmmlungMS;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="MeineSammlungen_3.Properties.Settings" SettingsPropertyName="SasmmlungMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Grunddaten" Member="Grunddaten">
    <Type Name="Grunddaten">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LfdNr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Modul" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nr" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Objekt" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Bemerkung" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ablageort" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ablageort_neu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Erstellt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Geaendert" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Checked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ImgCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Grunddaten_Ablage" Member="Ablage" ThisKey="Ablageort_neu" OtherKey="ID" Type="Ablage" />
      <Association Name="Module_Grunddaten" Member="Module" ThisKey="Modul" OtherKey="ID" Type="Module" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ModulMikro" Member="ModulMikro">
    <Type Name="ModulMikro">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Schnittebene" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Schnittart" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Farbung" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Aufhellung" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Fixierung" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Einschluss" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Hineise" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Grunddaten_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ablage" Member="Ablage">
    <Type Name="Ablage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ablageort" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Beschreibung" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="Grunddaten_Ablage" Member="Grunddaten" ThisKey="ID" OtherKey="Ablageort_neu" Type="Grunddaten" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Exponate" Member="Exponate">
    <Type Name="Exponate">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fundstelle_Land" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Fundstelle_Ort" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Koordinaten" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Hinweise" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Grunddaten_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fund_Datum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Settings">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Bildpfad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Bildtyp" Member="Bildtyp">
    <Type Name="Bildtyp">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Bildtyp" Member="Bildtyp1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Beschreibung" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mineralien" Member="Mineralien">
    <Type Name="Mineralien">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fundstelle_Land" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Fundstelle_Ort" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Koordinaten" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Hinweise" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Grunddaten_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fund_Datum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gewicht" Type="System.Single" DbType="Float" CanBeNull="true" />
      <Column Name="Volumen" Type="System.Single" DbType="Float" CanBeNull="true" />
      <Column Name="Dichte" Type="System.Single" DbType="Float" CanBeNull="true" />
      <Column Name="Zusammensetzung" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Journal" Member="Journal">
    <Type Name="Journal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Objekt" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Beschreibung" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Land" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Ort" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Postition" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="GPSPosition" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Bearbeitung" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="Funddatum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Bilder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InSammlung" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SammlungNr" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="InSammlungDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Journal_JournalImage" Member="JournalImage" ThisKey="ID" OtherKey="JournalNr" Type="JournalImage" />
    </Type>
  </Table>
  <Table Name="dbo.JournalImage" Member="JournalImage">
    <Type Name="JournalImage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="JournalNr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="PathFileName" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Association Name="Journal_JournalImage" Member="Journal" ThisKey="JournalNr" OtherKey="ID" Type="Journal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Module" Member="Module">
    <Type Name="Module">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Modul" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Beschreibung" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Module_Grunddaten" Member="Grunddaten" ThisKey="ID" OtherKey="Modul" Type="Grunddaten" />
    </Type>
  </Table>
</Database>